const data = [
    {
        id: 1,
        img : "./images/blog-exciting.jpg ",
        day: 3,
        month :'Nov',
        title: "Exciting News!",
        text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi contur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi.",
        category: "Initiatives",
    },
   
    
    {
        id: 2,
        img : "./images/blog-tech.jpg ",
        day: 6,
        month :'Oct',
        title: "Why Technology is Key",
        text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi contur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi.",
        category: "Technology",
    },
    {
        id: 3,
        img : "./images/blog-hospital.jpg ",
        day: 19,
        month :'Sept',
        title: "Inside Look at Our New Hospital",
        text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi contur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi.",
        category: "Hospitals",
    },
   
    {
        id: 4,
        img : "./images/blog-difference.jpg",
        day: 31,
        month :'Aug',
        title: "How We're Making a Difference",
        text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi contur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi.",
        category: "Initiatives",
    },
    {
        id: 5,
        img : "./images/blog-exciting.jpg ",
        day: 3,
        month :'Nov',
        title: "Exciting News!",
        text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi contur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi.",
        category: "Initiatives",
    },
    {
        id: 6,
        img : "./images/blog-difference.jpg",
        day: 31,
        month :'Aug',
        title: "How We're Making a Difference",
        text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi contur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi.",
        category: "Initiatives",
    },
    {
        id: 7,
        img : "./images/blog-hospital.jpg ",
        day: 19,
        month :'Sept',
        title: "Inside Look at Our New Hospital",
        text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi contur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi.",
        category: "Hospitals",
    },
    {
        id: 8,
        img : "./images/blog-difference.jpg",
        day: 31,
        month :'Aug',
        title: "How We're Making a Difference",
        text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi contur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi.",
        category: "Initiatives",
    },
    
    {
        id: 9,
        img : "./images/blog-difference.jpg",
        day: 31,
        month :'Aug',
        title: "How We're Making a Difference",
        text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi contur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi.",
        category: "Initiatives",
    },
    {
        id: 10,
        img : "./images/blog-difference.jpg",
        day: 31,
        month :'Aug',
        title: "How We're Making a Difference",
        text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi contur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi.",
        category: "Initiatives",
    },{
        id: 11,
        img : "./images/blog-difference.jpg",
        day: 31,
        month :'Aug',
        title: "How We're Making a Difference",
        text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi contur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi.",
        category: "Initiatives",
    },
    {
        id: 12,
        img : "./images/blog-tech.jpg ",
        day: 6,
        month :'Oct',
        title: "Why Technology is Key",
        text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi contur adipisicing elit. Minima optio inventore officia tempora quibusdam. Sequi.",
        category: "Technology",
    },
    
]
export default data